// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBovSXg9prtirZWnXBMNXBmf-PAJnWfi50',
    appId: '1:854012753724:web:9c7dc5b65a4652cd681039',
    messagingSenderId: '854012753724',
    projectId: 'arkinventory-1dde3',
    authDomain: 'arkinventory-1dde3.firebaseapp.com',
    storageBucket: 'arkinventory-1dde3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLN9F8C4KW5ns9WkK24KUpUj8dssU0p0',
    appId: '1:854012753724:android:37b4f29257fe93d5681039',
    messagingSenderId: '854012753724',
    projectId: 'arkinventory-1dde3',
    storageBucket: 'arkinventory-1dde3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDElzSTfCU1OZAZEcF70khy1YqRww8YFAk',
    appId: '1:854012753724:ios:f08605da00a1f549681039',
    messagingSenderId: '854012753724',
    projectId: 'arkinventory-1dde3',
    storageBucket: 'arkinventory-1dde3.appspot.com',
    iosBundleId: 'com.example.arkInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDElzSTfCU1OZAZEcF70khy1YqRww8YFAk',
    appId: '1:854012753724:ios:3e1ab60a83902b02681039',
    messagingSenderId: '854012753724',
    projectId: 'arkinventory-1dde3',
    storageBucket: 'arkinventory-1dde3.appspot.com',
    iosBundleId: 'com.example.arkInventory.RunnerTests',
  );
}
